export default [
    {
        id: 1,
        songName: 'song1',
        artist: 'artistName1',
        dateStreamed: '2024/09/01',
        streamCount: 1300,
        userId: 15,
    },
    {
        id: 2,
        songName: 'song2',
        artist: 'artistName2',
        dateStreamed: '2024/09/10',
        streamCount: 1360,
        userId: 18,
    },
    {
        id: 3,
        songName: 'song3',
        artist: 'artistName3',
        dateStreamed: '2024/08/16',
        streamCount: 1450,
        userId: 23,
    },
    {
        id: 4,
        songName: 'song4',
        artist: 'artistName4',
        dateStreamed: '2024/08/21',
        streamCount: 2000,
        userId: 30,
    },
    {
        id: 5,
        songName: 'song5',
        artist: 'artistName5',
        dateStreamed: '2024/08/24',
        streamCount: 1892,
        userId: 39,
    },
    {
        id: 6,
        songName: 'song6',
        artist: 'artistName6',
        dateStreamed: '2024/09/02',
        streamCount: 1298,
        userId: 15,
    },
    {
        id: 7,
        songName: 'song7',
        artist: 'artistName7',
        dateStreamed: '2024/09/11',
        streamCount: 1358,
        userId: 17,
    },
    {
        id: 8,
        songName: 'song8',
        artist: 'artistName8',
        dateStreamed: '2024/08/17',
        streamCount: 1448,
        userId: 21,
    },
    {
        id: 9,
        songName: 'song9',
        artist: 'artistName9',
        dateStreamed: '2024/08/22',
        streamCount: 1998,
        userId: 75,
    },
    {
        id: 10,
        songName:
            'song10 this is a super long name just for testing okay more word to fill the space',
        artist: 'artistName10 this is a super long name just for testing okay more word to fill the space',
        dateStreamed: '2024/08/25',
        streamCount: 1890,
        userId: 35,
    },
];
