version: '3.3'

services:
    app:
        build:
            context: ..
            dockerfile: ./docker/dev.dockerfile
        command: yarn dev
        volumes:
            - ..:/app
        ports:
            - ${APP_PORT}:${APP_PORT}
        environment:
            NODE_ENV: ${NODE_ENV}
            APP_PORT: ${APP_PORT}
            APP_HOST: ${APP_HOST}
