name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v1
      - name: Create .env file
        run: cp ./docker/dev.env .env
      - name: Install docker-compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0
          legacy: true
      - run: docker-compose --version
      - name: Test app
        run: docker-compose run app yarn test
